#!/usr/bin/php
<?php

#
# Command line executable installer
# To install run: sudo ./install
# Usage: markdownextra input1.md [input2.md ...] > output.html
#

$dir = dirname(__FILE__);

$code = "#!/usr/bin/php\n";
$code .= str_replace('?>', '', file_get_contents($dir . '/Michelf/MarkdownInterface.php'));
$code .= str_replace(array('?>', '<?php', 'namespace Michelf;'), '', file_get_contents($dir . '/Michelf/Markdown.php'));
$code .= str_replace(array('?>', '<?php', 'namespace Michelf;'), '', file_get_contents($dir . '/Michelf/MarkdownExtra.php'));
$code .= 'for ($i = 1; $i < $argc; $i++) echo MarkdownExtra::defaultTransform(file_get_contents($argv[$i]));';

$filename = '/usr/bin/markdownextra';

file_put_contents($filename, $code);
chmod($filename, 0755);
